# -*- coding: utf-8 -*-
"""shitDigitClassifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DpD8Ppp170AoWEymvDCXXWTEWkrUUNYy
"""

import tensorflow as tf
import keras
import numpy as np

(X_train, y_train), (X_test, y_test) = keras.datasets.mnist.load_data()

X_train= X_train/255
X_test = X_test/255

model = keras.models.Sequential(
[keras.layers.Flatten(input_shape=(28,28)),
keras.layers.Dense(128, activation = 'relu'),
keras.layers.Dense(10, activation= 'softmax')
]
)

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy',metrics=['accuracy'])

model.fit(X_train, y_train, epochs=5)

test_loss, test_acc = model.evaluate(X_test, y_test)

print(test_acc)